inventory:
  plugin: SimpleInventory
  options:
    host_file: "inventory/hosts.yaml"
    group_file: "inventory/groups.yaml"
    default_file: "inventory/defaults.yaml"

runner:
  plugin: threaded
  options:
    num_workers: 64

logging:
  enabled: True
  level: INFO
  log_file: nornir.log
