name: Build Multi-Platform Executables

on:
  [push]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nornir nornir-netmiko nornir-scrapli pyinstaller "scrapli[community]"

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --hidden-import=nornir_scrapli.driver.core.cisco_iosxr.driver --hidden-import=nornir_scrapli.driver.core.arista_eos.driver --hidden-import=nornir_scrapli.driver.core.juniper_junos.driver --hidden-import=nornir_scrapli.driver.core.cisco_iosxe.driver --hidden-import=nornir_scrapli.driver.core.cisco_nxos.driver --hidden-import=nornir_scrapli.driver.core.huawei_vrp.async_driver --hidden-import=nornir_scrapli.driver.core.h3c_vrp.async_driver --hidden-import=nornir_scrapli.driver.core.paloalto_panos.async_driver --hidden-import=nornir_scrapli.driver.core.fortinet_fortios.async_driver --hidden-import=scrapli_community.arista.eos.async_driver --hidden-import=scrapli_community.cisco.asa.async_driver --hidden-import=scrapli_community.cisco.iosxr.async_driver --hidden-import=scrapli_community.cisco.iosxe.async_driver --hidden-import=scrapli_community.cisco.nxos.async_driver --hidden-import=scrapli_community.fortinet.fortios.async_driver --hidden-import=scrapli_community.huawei.vrp.async_driver --hidden-import=scrapli_community.h3c.vrp.async_driver --hidden-import=scrapli_community.juniper.junos.async_driver --hidden-import=scrapli_community.nokia.sros.async_driver --hidden-import=scrapli_community.paloalto.panos.async_driver --hidden-import=nornir_scrapli.driver.core.juniper_evo.async_driver --hidden-import=scrapli_community.juniper.evo.async_driver my-app.py
        env:
          PYTHONUTF8: 1

      - name: Rename executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mv dist/my-app.exe dist/my-app-windows.exe

      - name: Rename executable (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mv dist/my-app dist/my-app-macos

      - name: Rename executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv dist/my-app dist/my-app-linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables-${{ matrix.os }}
          path: dist/
          if-no-files-found: error
